### ISSUE TITLE
Cryptol to Python test bench

### ISSUE THREAD

**Issue by b13decker** [GaloisInc/ckzg-eip-4844-verification#25]
We want to test out the following Cryptol functions against the corresponding Deneb Python Spec implementations:
- [x] [evaluate_polynomial_in_evaluation_form](https://github.com/GaloisInc/ckzg-eip-4844-verification/issues/new#evaluate_polynomial_in_evaluation_form): large inputs but all fixed sized values (`BlsPolynomial` is 4096 256-bit values)
- [x] [compute_quotient_eval_within_domain](https://github.com/GaloisInc/ckzg-eip-4844-verification/issues/new#compute_quotient_eval_within_domain): large inputs but all fixed sized values (`BlsPolynomial` is 4096 256-bit values)
- [x] [compute_kzg_proof_impl](https://github.com/GaloisInc/ckzg-eip-4844-verification/issues/new#compute_kzg_proof_impl):  arge inputs but all fixed sized values (`BlsPolynomial` is 4096 256-bit values)
- [x] [compute_kzg_proof](https://github.com/GaloisInc/ckzg-eip-4844-verification/issues/new#compute_kzg_proof) arge inputs but all fixed sized values (`BlsBlob` is the same size as the `BlsPolynomial`)
- [x] [verify_kzg_proof_impl](https://github.com/GaloisInc/ckzg-eip-4844-verification/issues/new#verify_kzg_proof_impl): for this one we will need to create a generator for G1 points
- [x] [verify_kzg_proof](https://github.com/GaloisInc/ckzg-eip-4844-verification/issues/new#verify_kzg_proof): for this one we will need to create a generator for G1 points that then get compressed

**Comment by mccleeary-galois** [comment]
[compute_kzg_proof](https://github.com/GaloisInc/ckzg-eip-4844-verification/issues/new#compute_kzg_proof)
This has taken over 2 hours of run time with no output on randomly generated input, unsure if it is terminating.
