### ISSUE TITLE
Add top level docstrings in Cryptol modules

### ISSUE THREAD

**Issue by b13decker** [GaloisInc/ckzg-eip-4844-verification#9]
When Saw 1.2 is released with Cryptol 3.2 we can opt to have top level docstrings if we want.

_Originally posted by @mccleeary-galois in https://github.com/GaloisInc/ckzg-eip-4844-verification/pull/7#discussion_r1739011598_

**Comment by mccleeary-galois** [comment]
https://github.com/GaloisInc/saw-script/releases/tag/v1.2
